### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by ssaarela**

### CODE REVIEW

**Comment by ssaarela** [comment]
@paazmaya This needs your approval for Codecov access to finnair organization.

**Comment by eostman** [comment]
Wouldn't it make sense to have the code coverage as a separate workflow?

**Comment by ssaarela** [comment]
> Wouldn't it make sense to have the code coverage as a separate workflow?

Would it? 🤷‍♂ It's just one additional parameter (--coverage) and a step that sends the report. What would be the benefit of separating them?

**Comment by ssaarela** [comment]
Maybe, only using one Node version for coverage as that makes no difference to it?

**Comment by eostman** [comment]
It would be visible here in a PR as a 4th check, instead of being part of the CI / scripts. 

Perhaps in the future you would like it to fail if coverage drops on new code?

**Comment by ssaarela** [comment]
Good point. Would you be willing to contribute that setup? I've little to no experience in GH Actions...

**Comment by eostman** [comment]
I can try to cook something up today, or tomorrow :)

**Comment by ssaarela** [comment]
Soved by https://github.com/finnair/v-validation/pull/17

**Pull request closed without merging**
